---
name: test

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: run unit tests
        run: go test -v -count=1 . ./tasks/ ./subprocess/

  integration-test:
    name: integration-test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: enable docker legacy link support
        run: |
          sudo mkdir -p /etc/systemd/system/docker.service.d
          printf '[Service]\nEnvironment="DOCKER_KEEP_DEPRECATED_LEGACY_LINKS_ENV_VARS=1"\n' | sudo tee /etc/systemd/system/docker.service.d/legacy-links.conf
          sudo systemctl daemon-reload
          sudo systemctl restart docker
      - name: install dokku
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://packagecloud.io/dokku/dokku/gpgkey | sudo gpg --dearmor -o /etc/apt/keyrings/dokku-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/dokku-archive-keyring.gpg] https://packagecloud.io/dokku/dokku/ubuntu/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/dokku.list
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -qq -y dokku
          sudo dokku plugin:install-dependencies --core
      - name: install dokku redis plugin
        run: sudo dokku plugin:install https://github.com/dokku/dokku-redis.git redis
      - name: install dokku http-auth plugin
        run: sudo dokku plugin:install https://github.com/dokku/dokku-http-auth.git http-auth
      - name: install dokku global-cert plugin
        run: sudo dokku plugin:install https://github.com/dokku-community/dokku-global-cert.git global-cert
      - name: install dokku letsencrypt plugin
        run: sudo dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git letsencrypt
      - name: run integration tests
        run: sudo go test -v -count=1 -run TestIntegration ./tasks/
